name: Increase Code Coverage
description: Increases code coverage thresholds
branding:
  color: green
  icon: eye
inputs:
  config-key:
    description: 'Cache key used for caching config file in test runner job (e.g. ${{ runner.os }}-cache-jest-config)'
    required: true
  config-path:
    description: 'Path to test config file (e.g. ../jest.config.js)'
    required: true
  summary-key:
    description: 'Cache key used for caching the generated code coverage summary JSON file (e.g. ${{ runner.os }}-cache-coverage-summary)'
    required: true
  summary-path:
    description: 'Path to generated code coverage summary JSON file (e.g. ../coverage/coverage-summary.json)'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
